// PlaybookOS — Permission Registry (SEED / DATA ONLY)
// Generated from the P1 manifest: 185 API routes / 24 nav pages + 8 routed-only / 31 crons.
// cost/spend/dangerous are the values traced from handler bodies in P1 (incl. the 8 corrected rows).
// NOTHING imports this file yet. It defines the catalog of individually permission-controllable
// surfaces. Role templates may grant defaultDeny:false features; defaultDeny:true features
// (every high-cost or dangerous action, every cron, every manual agent trigger) require an
// explicit per-user grant and are never handed out by a template.
//
// implies: a nav_page grants the initial-render GET reads it needs. Per policy a page NEVER
// implies a write, a spend action, or an adminOnly route — those are listed as separate
// features and noted in a comment on the page entry.

module.exports = {
  FEATURES: [

    // ===================== NAV PAGES (24 nav + 8 routed-only) =====================
  {
    key: 'platform.page_command_center.view',
    label: "Command Center (page)",
    domain: 'platform',
    surface: 'nav_page',
    ref: "command-center",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['intelligence.briefing_latest.list', 'team.goals_team_week.list', 'revenue.customers_warm_leads.list', 'revenue.customers_outreach_today.list', 'intelligence.metrics_today.list'],
    defaultDeny: false,
  },
  {
    // excluded from implies (Rule 2 — separate features): GET /api/agent/overview [adminOnly]; GET /api/agent/tasks/team [adminOnly]
    key: 'revenue.page_dashboard.view',
    label: "Dashboard (page)",
    domain: 'revenue',
    surface: 'nav_page',
    ref: "dashboard",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['personal.dashboard_summary.list', 'personal.agent_tasks_my.list'],
    defaultDeny: false,
  },
  {
    // excluded from implies (Rule 2 — separate features): GET /api/performance/alerts [adminOnly]
    key: 'team.page_performance.view',
    label: "Performance (page)",
    domain: 'team',
    surface: 'nav_page',
    ref: "performance",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['team.performance_team.list'],
    defaultDeny: false,
  },
  {
    key: 'revenue.page_revenue.view',
    label: "Revenue & Orders (page)",
    domain: 'revenue',
    surface: 'nav_page',
    ref: "revenue",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['revenue.orders.list'],
    defaultDeny: false,
  },
  {
    key: 'revenue.page_sales_pipeline.view',
    label: "Sales Pipeline (page)",
    domain: 'revenue',
    surface: 'nav_page',
    ref: "sales-pipeline",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['revenue.leads_pipeline.list', 'revenue.leads.list'],
    defaultDeny: false,
  },
  {
    key: 'revenue.page_reorder_agent.view',
    label: "Reorder Agent (page)",
    domain: 'revenue',
    surface: 'nav_page',
    ref: "reorder-agent",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['revenue.reorder_dashboard.list', 'revenue.reorder_candidates.list', 'revenue.reorder_campaigns.list', 'revenue.reorder_buyers.list'],
    defaultDeny: false,
  },
  {
    key: 'revenue.page_inquiry_agent.view',
    label: "Inquiry Agent (page)",
    domain: 'revenue',
    surface: 'nav_page',
    ref: "inquiry-agent",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['revenue.inquiry_dashboard.list', 'revenue.inquiry.list', 'revenue.inquiry_pricing.list', 'revenue.inquiry_pipeline.list'],
    defaultDeny: false,
  },
  {
    // excluded from implies (Rule 2 — separate features): GET /api/apollo/stats [low/apollo spend]
    key: 'revenue.page_apollo_outreach.view',
    label: "Apollo Outreach (page)",
    domain: 'revenue',
    surface: 'nav_page',
    ref: "apollo-outreach",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.page_email_engine.view',
    label: "Email Engine (page)",
    domain: 'revenue',
    surface: 'nav_page',
    ref: "email-engine",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['revenue.email_engine_campaigns.list'],
    defaultDeny: false,
  },
  {
    // excluded from implies (Rule 2 — separate features): PUT /api/prospects/:id [write];
    // POST /api/prospects/run + /qualify [adminOnly, high]
    key: 'revenue.page_prospects.view',
    label: "Prospects (page)",
    domain: 'revenue',
    surface: 'nav_page',
    ref: "prospects",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['revenue.prospects.list'],
    defaultDeny: false,
  },
  {
    key: 'intelligence.page_market_intelligence.view',
    label: "Market Intelligence (page)",
    domain: 'intelligence',
    surface: 'nav_page',
    ref: "market-intelligence",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['intelligence.market_weekly.list'],
    defaultDeny: false,
  },
  {
    // excluded from implies (Rule 2 — separate features): GET /api/procurement/compare/:rfqId [high/llm spend]
    key: 'procurement.page_procurement_agent.view',
    label: "Procurement Agent (page)",
    domain: 'procurement',
    surface: 'nav_page',
    ref: "procurement-agent",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['procurement.procurement_dashboard.list', 'procurement.procurement_rfqs.list', 'procurement.procurement_suppliers.list'],
    defaultDeny: false,
  },
  {
    // excluded from implies (Rule 2 — separate features): GET /api/meetings/workspace-activity [adminOnly]
    key: 'intelligence.page_meet_agent.view',
    label: "Google Meet Agent (page)",
    domain: 'intelligence',
    surface: 'nav_page',
    ref: "meet-agent",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['intelligence.meetings_dashboard.list', 'intelligence.meetings.list', 'admin.users.list', 'intelligence.meetings.get'],
    defaultDeny: false,
  },
  {
    key: 'intelligence.page_research_agent.view',
    label: "Research Agent (page)",
    domain: 'intelligence',
    surface: 'nav_page',
    ref: "research-agent",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['intelligence.research_dashboard.list', 'intelligence.research_findings.list', 'intelligence.research_patents.list', 'intelligence.research_report.list'],
    defaultDeny: false,
  },
  {
    key: 'intelligence.page_clinical_demand_intelligence.view',
    label: "Clinical Demand Intelligence (page)",
    domain: 'intelligence',
    surface: 'nav_page',
    ref: "clinical-demand-intelligence",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['intelligence.research_intelligence_studies.list'],
    defaultDeny: false,
  },
  {
    // excluded from implies (Rule 2 — separate features): PUT /api/content/:id [write];
    // POST /api/content/run [adminOnly, high/llm]
    key: 'intelligence.page_content_studio.view',
    label: "Content Studio (page)",
    domain: 'intelligence',
    surface: 'nav_page',
    ref: "content-studio",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['intelligence.content.list'],
    defaultDeny: false,
  },
  {
    key: 'growth.page_seo_intelligence.view',
    label: "SEO Intelligence (page)",
    domain: 'growth',
    surface: 'nav_page',
    ref: "seo-intelligence",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['growth.seo_rankings.list', 'growth.seo_gaps.list', 'growth.seo_no_results.list'],
    defaultDeny: false,
  },
  {
    key: 'growth.page_seo_content.view',
    label: "SEO Content (page)",
    domain: 'growth',
    surface: 'nav_page',
    ref: "seo-content",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['growth.seo_content_queue.list'],
    defaultDeny: false,
  },
  {
    key: 'growth.page_linkedin_content.view',
    label: "LinkedIn Content (page)",
    domain: 'growth',
    surface: 'nav_page',
    ref: "linkedin-content",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['growth.linkedin_content_queue.list', 'growth.linkedin_analytics.list', 'growth.linkedin_demand_molecules.list'],
    defaultDeny: false,
  },
  {
    key: 'personal.page_my_tasks.view',
    label: "My Tasks (page)",
    domain: 'personal',
    surface: 'nav_page',
    ref: "my-tasks",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['personal.agent_tasks_my.list', 'personal.performance_my.list'],
    defaultDeny: false,
  },
  {
    key: 'personal.page_my_kpis.view',
    label: "My KPIs (page)",
    domain: 'personal',
    surface: 'nav_page',
    ref: "my-kpis",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['personal.goals_my_week.list'],
    defaultDeny: false,
  },
  {
    key: 'personal.page_my_performance.view',
    label: "My Performance (page)",
    domain: 'personal',
    surface: 'nav_page',
    ref: "my-performance",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['personal.performance_my.list'],
    defaultDeny: false,
  },
  {
    key: 'team.page_team.view',
    label: "Team Management (page)",
    domain: 'team',
    surface: 'nav_page',
    ref: "team",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['admin.users.list', 'admin.roles.list'],
    defaultDeny: false,
  },
  {
    // excluded from implies (Rule 2 — separate features): GET /api/agent/overview [adminOnly]; GET /api/agent/activity [adminOnly]; GET /api/agent/approvals [adminOnly]; GET /api/agent/mission-control [adminOnly]
    key: 'admin.page_agent_control.view',
    label: "Agent Control (page)",
    domain: 'admin',
    surface: 'nav_page',
    ref: "agent-control",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['admin.agent_dependencies.list', 'admin.users.list'],
    defaultDeny: false,
  },
  {
    key: 'procurement.page_sku_economics.view',
    label: "SKU Economics (page)",
    domain: 'procurement',
    surface: 'nav_page',
    ref: "sku-economics",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['procurement.skus.list'],
    defaultDeny: false,
  },
  {
    key: 'platform.page_settings.view',
    label: "Settings (page)",
    domain: 'platform',
    surface: 'nav_page',
    ref: "settings",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.page_my_activity.view',
    label: "My Activity (page)",
    domain: 'personal',
    surface: 'nav_page',
    ref: "my-activity",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['admin.roles.list', 'personal.activity_my.list'],
    defaultDeny: false,
  },
  {
    key: 'personal.page_playbook.view',
    label: "Playbook (page)",
    domain: 'personal',
    surface: 'nav_page',
    ref: "playbook",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.page_milestones.view',
    label: "Milestones (page)",
    domain: 'personal',
    surface: 'nav_page',
    ref: "milestones",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['personal.milestones.list'],
    defaultDeny: false,
  },
  {
    key: 'intelligence.page_ai_insights.view',
    label: "AI Insights (page)",
    domain: 'intelligence',
    surface: 'nav_page',
    ref: "ai-insights",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['intelligence.ai_latest.list'],
    defaultDeny: false,
  },
  {
    key: 'intelligence.page_decision_engine.view',
    label: "Automation Rules (page)",
    domain: 'intelligence',
    surface: 'nav_page',
    ref: "decision-engine",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['intelligence.decision_rules.list'],
    defaultDeny: false,
  },
  {
    key: 'platform.page_data_pipeline.view',
    label: "Data Pipeline (page)",
    domain: 'platform',
    surface: 'nav_page',
    ref: "data-pipeline",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['platform.integrations.list'],
    defaultDeny: false,
  },
  {
    key: 'platform.page_execution_graph.view',
    label: "Execution Graph (page)",
    domain: 'platform',
    surface: 'nav_page',
    ref: "execution-graph",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['platform.execution_steps.list'],
    defaultDeny: false,
  },
  {
    key: 'team.page_employee_activity.view',
    label: "Employee Activity (page)",
    domain: 'team',
    surface: 'nav_page',
    ref: "employee-activity",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: ['admin.users.list', 'team.employee_activity.get'],
    defaultDeny: false,
  },

    // ===================== API ROUTES (gated) =====================
  {
    key: 'personal.auth_me.list',
    label: "List — GET /api/auth/me",
    domain: 'personal',
    surface: 'api_route',
    ref: "GET /api/auth/me",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.roles.list',
    label: "List — GET /api/roles",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/roles",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.roles.create',
    label: "Create — POST /api/roles",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/roles",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.users.list',
    label: "List — GET /api/users",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/users",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.users.invite',
    label: "Invite — POST /api/users/invite",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/users/invite",
    cost: 'low',
    spend: ['email'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'personal.users_profile.update',
    label: "Update — PUT /api/users/profile",
    domain: 'personal',
    surface: 'api_route',
    ref: "PUT /api/users/profile",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.users.update',
    label: "Update — PUT /api/users/:id",
    domain: 'admin',
    surface: 'api_route',
    ref: "PUT /api/users/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.users.delete',
    label: "Delete — DELETE /api/users/:id",
    domain: 'admin',
    surface: 'api_route',
    ref: "DELETE /api/users/:id",
    cost: 'free',
    spend: [],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.users_toggle_status.update',
    label: "Update — PUT /api/users/:id/toggle-status",
    domain: 'admin',
    surface: 'api_route',
    ref: "PUT /api/users/:id/toggle-status",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.admin_users.reset_password',
    label: "Reset password — POST /api/admin/users/:user_id/reset-password",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/admin/users/:user_id/reset-password",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.admin_users.edit_name',
    label: "Edit name — POST /api/admin/users/:user_id/edit-name",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/admin/users/:user_id/edit-name",
    cost: 'low',
    spend: ['email'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.users.send_onboarding',
    label: "Send onboarding — POST /api/users/send-onboarding",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/users/send-onboarding",
    cost: 'low',
    spend: ['email'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.users.send_task_nudge',
    label: "Send task nudge — POST /api/users/send-task-nudge",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/users/send-task-nudge",
    cost: 'low',
    spend: ['email'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'platform.activity.create',
    label: "Create — POST /api/activity",
    domain: 'platform',
    surface: 'api_route',
    ref: "POST /api/activity",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.activity_my.list',
    label: "List — GET /api/activity/my",
    domain: 'personal',
    surface: 'api_route',
    ref: "GET /api/activity/my",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'team.employee_activity.get',
    label: "Get — GET /api/employee-activity/:user_id",
    domain: 'team',
    surface: 'api_route',
    ref: "GET /api/employee-activity/:user_id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'team.activity_team.list',
    label: "List — GET /api/activity/team",
    domain: 'team',
    surface: 'api_route',
    ref: "GET /api/activity/team",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.orders.create',
    label: "Create — POST /api/orders",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/orders",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.orders.list',
    label: "List — GET /api/orders",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/orders",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.dashboard_summary.list',
    label: "List — GET /api/dashboard/summary",
    domain: 'personal',
    surface: 'api_route',
    ref: "GET /api/dashboard/summary",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.dashboard_export.list',
    label: "List — GET /api/dashboard/export",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/dashboard/export",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.dashboard_my.list',
    label: "List — GET /api/dashboard/my",
    domain: 'personal',
    surface: 'api_route',
    ref: "GET /api/dashboard/my",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'platform.github.sync',
    label: "Sync — POST /api/github/sync",
    domain: 'platform',
    surface: 'api_route',
    ref: "POST /api/github/sync",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.milestones.list',
    label: "List — GET /api/milestones",
    domain: 'personal',
    surface: 'api_route',
    ref: "GET /api/milestones",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.milestones.update',
    label: "Update — PUT /api/milestones/:id",
    domain: 'personal',
    surface: 'api_route',
    ref: "PUT /api/milestones/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.ai.analyze',
    label: "Analyze — POST /api/ai/analyze",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/ai/analyze",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.ai_latest.list',
    label: "List — GET /api/ai/latest",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/ai/latest",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.targets.list',
    label: "List — GET /api/targets",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/targets",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.targets.create',
    label: "Create — POST /api/targets",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/targets",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.decision_rules.list',
    label: "List — GET /api/decision-rules",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/decision-rules",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.decision_rules.evaluate',
    label: "Evaluate — POST /api/decision-rules/evaluate",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/decision-rules/evaluate",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.skus.list',
    label: "List — GET /api/skus",
    domain: 'procurement',
    surface: 'api_route',
    ref: "GET /api/skus",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.skus.create',
    label: "Create — POST /api/skus",
    domain: 'procurement',
    surface: 'api_route',
    ref: "POST /api/skus",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'platform.execution_steps.list',
    label: "List — GET /api/execution-steps",
    domain: 'platform',
    surface: 'api_route',
    ref: "GET /api/execution-steps",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'platform.execution_steps.update',
    label: "Update — PUT /api/execution-steps/:id",
    domain: 'platform',
    surface: 'api_route',
    ref: "PUT /api/execution-steps/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'platform.integrations.list',
    label: "List — GET /api/integrations",
    domain: 'platform',
    surface: 'api_route',
    ref: "GET /api/integrations",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.linkedin_log.create',
    label: "Create — POST /api/linkedin/log",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/linkedin/log",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.linkedin_pipeline.list',
    label: "List — GET /api/linkedin/pipeline",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/linkedin/pipeline",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.metrics_today.list',
    label: "List — GET /api/metrics/today",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/metrics/today",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.metrics_history.list',
    label: "List — GET /api/metrics/history",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/metrics/history",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.customers_warm_leads.list',
    label: "List — GET /api/customers/warm-leads",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/customers/warm-leads",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.customers_outreach_today.list',
    label: "List — GET /api/customers/outreach-today",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/customers/outreach-today",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'team.goals.cascade',
    label: "Cascade — POST /api/goals/cascade",
    domain: 'team',
    surface: 'api_route',
    ref: "POST /api/goals/cascade",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'team.goals.assign_kpis',
    label: "Assign kpis — POST /api/goals/assign-kpis",
    domain: 'team',
    surface: 'api_route',
    ref: "POST /api/goals/assign-kpis",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.goals_my_week.list',
    label: "List — GET /api/goals/my-week",
    domain: 'personal',
    surface: 'api_route',
    ref: "GET /api/goals/my-week",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'team.goals_team_week.list',
    label: "List — GET /api/goals/team-week",
    domain: 'team',
    surface: 'api_route',
    ref: "GET /api/goals/team-week",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.kpis_progress.update',
    label: "Update — PUT /api/kpis/:id/progress",
    domain: 'personal',
    surface: 'api_route',
    ref: "PUT /api/kpis/:id/progress",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.seo_rankings.list',
    label: "List — GET /api/seo/rankings",
    domain: 'growth',
    surface: 'api_route',
    ref: "GET /api/seo/rankings",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.seo_rankings.create',
    label: "Create — POST /api/seo/rankings",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/seo/rankings",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.seo_gaps.list',
    label: "List — GET /api/seo/gaps",
    domain: 'growth',
    surface: 'api_route',
    ref: "GET /api/seo/gaps",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.seo_gaps.create',
    label: "Create — POST /api/seo/gaps",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/seo/gaps",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.seo_no_results.list',
    label: "List — GET /api/seo/no-results",
    domain: 'growth',
    surface: 'api_route',
    ref: "GET /api/seo/no-results",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.seo_no_results.create',
    label: "Create — POST /api/seo/no-results",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/seo/no-results",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.seo.generate_content',
    label: "Generate content — POST /api/seo/generate-content",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/seo/generate-content",
    cost: 'medium',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.seo.generate_catalog',
    label: "Generate catalog — POST /api/seo/generate-catalog",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/seo/generate-catalog",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.seo_catalog_status.list',
    label: "List — GET /api/seo/catalog-status",
    domain: 'growth',
    surface: 'api_route',
    ref: "GET /api/seo/catalog-status",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.seo_content_queue.list',
    label: "List — GET /api/seo/content-queue",
    domain: 'growth',
    surface: 'api_route',
    ref: "GET /api/seo/content-queue",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.growth.analyze',
    label: "Analyze — POST /api/growth/analyze",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/growth/analyze",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.growth_intelligence.list',
    label: "List — GET /api/growth/intelligence",
    domain: 'growth',
    surface: 'api_route',
    ref: "GET /api/growth/intelligence",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.briefing_latest.list',
    label: "List — GET /api/briefing/latest",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/briefing/latest",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.revenue_intelligence.list',
    label: "List — GET /api/revenue/intelligence",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/revenue/intelligence",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.performance_scores.list',
    label: "List — GET /api/performance/scores",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/performance/scores",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'team.performance_team.list',
    label: "List — GET /api/performance/team",
    domain: 'team',
    surface: 'api_route',
    ref: "GET /api/performance/team",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.performance_my.list',
    label: "List — GET /api/performance/my",
    domain: 'personal',
    surface: 'api_route',
    ref: "GET /api/performance/my",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.performance_alerts.list',
    label: "List — GET /api/performance/alerts",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/performance/alerts",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.performance_history.get',
    label: "Get — GET /api/performance/history/:userId",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/performance/history/:userId",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.performance.calculate',
    label: "Calculate — POST /api/performance/calculate",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/performance/calculate",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.milestones_duplicates.delete',
    label: "Delete — DELETE /api/milestones/duplicates",
    domain: 'admin',
    surface: 'api_route',
    ref: "DELETE /api/milestones/duplicates",
    cost: 'free',
    spend: [],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.market.analyze',
    label: "Analyze — POST /api/market/analyze",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/market/analyze",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.email_engine.run',
    label: "Run — POST /api/email-engine/run",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/email-engine/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.email_engine_campaigns.list',
    label: "List — GET /api/email-engine/campaigns",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/email-engine/campaigns",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.email_engine_campaigns.update',
    label: "Update — PUT /api/email-engine/campaigns/:id",
    domain: 'revenue',
    surface: 'api_route',
    ref: "PUT /api/email-engine/campaigns/:id",
    cost: 'high',
    spend: ['apollo'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.email_engine_campaigns.publish',
    label: "Publish — POST /api/email-engine/campaigns/:id/publish",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/email-engine/campaigns/:id/publish",
    cost: 'high',
    spend: ['apollo'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.email_engine_campaigns_preview.get',
    label: "Get — GET /api/email-engine/campaigns/:id/preview",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/email-engine/campaigns/:id/preview",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry.run',
    label: "Run — POST /api/inquiry/run",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/inquiry/run",
    cost: 'high',
    spend: ['llm', 'email'], // A2: runInquiryAgent sends buyer auto-replies + notifications (inquiry-agent.js:247/666/737/1115)
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.inquiry_dashboard.list',
    label: "List — GET /api/inquiry/dashboard",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/inquiry/dashboard",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry_pricing.list',
    label: "List — GET /api/inquiry/pricing",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/inquiry/pricing",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry_pipeline.list',
    label: "List — GET /api/inquiry/pipeline",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/inquiry/pipeline",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry_pricing.update',
    label: "Update — PUT /api/inquiry/pricing/:id",
    domain: 'revenue',
    surface: 'api_route',
    ref: "PUT /api/inquiry/pricing/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry.list',
    label: "List — GET /api/inquiry",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/inquiry",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry.get',
    label: "Get — GET /api/inquiry/:id",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/inquiry/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry.reply',
    label: "Reply — POST /api/inquiry/:id/reply",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/inquiry/:id/reply",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry.quote',
    label: "Quote — POST /api/inquiry/:id/quote",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/inquiry/:id/quote",
    cost: 'medium',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry.escalate',
    label: "Escalate — POST /api/inquiry/:id/escalate",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/inquiry/:id/escalate",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry.accept',
    label: "Accept — POST /api/inquiry/:id/accept",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/inquiry/:id/accept",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry.payment_received',
    label: "Payment received — POST /api/inquiry/:id/payment-received",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/inquiry/:id/payment-received",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.inquiry.update',
    label: "Update — PUT /api/inquiry/:id",
    domain: 'revenue',
    surface: 'api_route',
    ref: "PUT /api/inquiry/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.reorder.run',
    label: "Run — POST /api/reorder/run",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/reorder/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.reorder_dashboard.list',
    label: "List — GET /api/reorder/dashboard",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/reorder/dashboard",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.reorder_candidates.list',
    label: "List — GET /api/reorder/candidates",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/reorder/candidates",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.reorder_buyers.list',
    label: "List — GET /api/reorder/buyers",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/reorder/buyers",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.reorder_buyers.create',
    label: "Create — POST /api/reorder/buyers",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/reorder/buyers",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.reorder_buyers.update',
    label: "Update — PUT /api/reorder/buyers/:id",
    domain: 'revenue',
    surface: 'api_route',
    ref: "PUT /api/reorder/buyers/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.reorder_campaigns.list',
    label: "List — GET /api/reorder/campaigns",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/reorder/campaigns",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.reorder_campaigns.update',
    label: "Update — PUT /api/reorder/campaigns/:id",
    domain: 'revenue',
    surface: 'api_route',
    ref: "PUT /api/reorder/campaigns/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.research.run',
    label: "Run — POST /api/research/run",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/research/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.research_dashboard.list',
    label: "List — GET /api/research/dashboard",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/research/dashboard",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.research_findings.list',
    label: "List — GET /api/research/findings",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/research/findings",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.research_patents.list',
    label: "List — GET /api/research/patents",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/research/patents",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.research_patents.create',
    label: "Create — POST /api/research/patents",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/research/patents",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.research_findings.update',
    label: "Update — PUT /api/research/findings/:id",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "PUT /api/research/findings/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.research_report.list',
    label: "List — GET /api/research/report",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/research/report",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.meetings.run',
    label: "Run — POST /api/meetings/run",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/meetings/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.meetings.upload_transcript',
    label: "Upload transcript — POST /api/meetings/upload-transcript",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/meetings/upload-transcript",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.meetings.standup',
    label: "Standup — POST /api/meetings/standup",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/meetings/standup",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.meetings.poll_gemini',
    label: "Poll gemini — POST /api/meetings/poll-gemini",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/meetings/poll-gemini",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.meetings.sync_workspace',
    label: "Sync workspace — POST /api/meetings/sync-workspace",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/meetings/sync-workspace",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.meetings.transcript',
    label: "Transcript — POST /api/meetings/:id/transcript",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/meetings/:id/transcript",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.meetings_dashboard.list',
    label: "List — GET /api/meetings/dashboard",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/meetings/dashboard",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.meetings_workspace_activity.list',
    label: "List — GET /api/meetings/workspace-activity",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/meetings/workspace-activity",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.meetings.list',
    label: "List — GET /api/meetings",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/meetings",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.meetings.get',
    label: "Get — GET /api/meetings/:id",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/meetings/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.meetings_tasks.get',
    label: "Get — GET /api/meetings/:id/tasks",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/meetings/:id/tasks",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.meetings_tasks.update',
    label: "Update — PUT /api/meetings/tasks/:id",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "PUT /api/meetings/tasks/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.procurement.run',
    label: "Run — POST /api/procurement/run",
    domain: 'procurement',
    surface: 'api_route',
    ref: "POST /api/procurement/run",
    cost: 'high',
    spend: ['llm', 'email'], // A2: runProcurementAgent dispatches supplier RFQ emails + summaries (procurement-agent.js:357/463/469)
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'procurement.procurement_dashboard.list',
    label: "List — GET /api/procurement/dashboard",
    domain: 'procurement',
    surface: 'api_route',
    ref: "GET /api/procurement/dashboard",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.procurement_rfqs.list',
    label: "List — GET /api/procurement/rfqs",
    domain: 'procurement',
    surface: 'api_route',
    ref: "GET /api/procurement/rfqs",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.procurement_rfqs.get',
    label: "Get — GET /api/procurement/rfqs/:id",
    domain: 'procurement',
    surface: 'api_route',
    ref: "GET /api/procurement/rfqs/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.procurement_rfqs.responses',
    label: "Responses — POST /api/procurement/rfqs/:id/responses",
    domain: 'procurement',
    surface: 'api_route',
    ref: "POST /api/procurement/rfqs/:id/responses",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'procurement.procurement_compare.get',
    label: "Get — GET /api/procurement/compare/:rfqId",
    domain: 'procurement',
    surface: 'api_route',
    ref: "GET /api/procurement/compare/:rfqId",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'procurement.procurement_rfqs.approve_supplier',
    label: "Approve supplier — POST /api/procurement/rfqs/:id/approve-supplier",
    domain: 'procurement',
    surface: 'api_route',
    ref: "POST /api/procurement/rfqs/:id/approve-supplier",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.procurement_suppliers.list',
    label: "List — GET /api/procurement/suppliers",
    domain: 'procurement',
    surface: 'api_route',
    ref: "GET /api/procurement/suppliers",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.procurement_suppliers.create',
    label: "Create — POST /api/procurement/suppliers",
    domain: 'procurement',
    surface: 'api_route',
    ref: "POST /api/procurement/suppliers",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.procurement_suppliers.update',
    label: "Update — PUT /api/procurement/suppliers/:id",
    domain: 'procurement',
    surface: 'api_route',
    ref: "PUT /api/procurement/suppliers/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.seo.push_to_abiozen',
    label: "Push to abiozen — POST /api/seo/push-to-abiozen",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/seo/push-to-abiozen",
    cost: 'high',
    spend: ['llm'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.leads.list',
    label: "List — GET /api/leads",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/leads",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.leads_pipeline.list',
    label: "List — GET /api/leads/pipeline",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/leads/pipeline",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.leads.update',
    label: "Update — PUT /api/leads/:id",
    domain: 'revenue',
    surface: 'api_route',
    ref: "PUT /api/leads/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.leads_follow_ups.get',
    label: "Get — GET /api/leads/:id/follow-ups",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/leads/:id/follow-ups",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.leads_follow_up.create',
    label: "Create — POST /api/leads/:id/follow-up",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/leads/:id/follow-up",
    cost: 'medium',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.leads.process_replies',
    label: "Process replies — POST /api/leads/process-replies",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/leads/process-replies",
    cost: 'high',
    spend: ['apollo'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.market_weekly.list',
    label: "List — GET /api/market/weekly",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/market/weekly",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.market_history.list',
    label: "List — GET /api/market/history",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/market/history",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.market_molecule.update',
    label: "Update — PUT /api/market/molecule/:id",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "PUT /api/market/molecule/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.market_gaps.list',
    label: "List — GET /api/market/gaps",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/market/gaps",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.market_export_research.list',
    label: "List — GET /api/market/export/research",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/market/export/research",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.market_export_gmp.list',
    label: "List — GET /api/market/export/gmp",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/market/export/gmp",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.skus.bulk_upload',
    label: "Bulk upload — POST /api/skus/bulk-upload",
    domain: 'procurement',
    surface: 'api_route',
    ref: "POST /api/skus/bulk-upload",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'procurement.algolia.sync',
    label: "Sync — POST /api/algolia/sync",
    domain: 'procurement',
    surface: 'api_route',
    ref: "POST /api/algolia/sync",
    cost: 'free',
    spend: [],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'procurement.algolia.sync_abiozen',
    label: "Sync abiozen — POST /api/algolia/sync-abiozen",
    domain: 'procurement',
    surface: 'api_route',
    ref: "POST /api/algolia/sync-abiozen",
    cost: 'free',
    spend: [],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'procurement.skus_export.list',
    label: "List — GET /api/skus/export",
    domain: 'procurement',
    surface: 'api_route',
    ref: "GET /api/skus/export",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.apollo.find_buyers',
    label: "Find buyers — POST /api/apollo/find-buyers",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/apollo/find-buyers",
    cost: 'high',
    spend: ['apollo'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.apollo.send_outreach',
    label: "Send outreach — POST /api/apollo/send-outreach",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/apollo/send-outreach",
    cost: 'low',
    spend: ['email'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.apollo_sequences.list',
    label: "List — GET /api/apollo/sequences",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/apollo/sequences",
    cost: 'low',
    spend: ['apollo'],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.apollo_stats.list',
    label: "List — GET /api/apollo/stats",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/apollo/stats",
    cost: 'low',
    spend: ['apollo'],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.sequences_templates.list',
    label: "List — GET /api/sequences/templates",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/sequences/templates",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.apollo_debug.list',
    label: "List — GET /api/apollo/debug",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/apollo/debug",
    cost: 'low',
    spend: ['apollo'],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'personal.agent_tasks_my.list',
    label: "List — GET /api/agent/tasks/my",
    domain: 'personal',
    surface: 'api_route',
    ref: "GET /api/agent/tasks/my",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.agent_tasks.update',
    label: "Update — PUT /api/agent/tasks/:id",
    domain: 'admin',
    surface: 'api_route',
    ref: "PUT /api/agent/tasks/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'team.agent_tasks_team.list',
    label: "List — GET /api/agent/tasks/team",
    domain: 'team',
    surface: 'api_route',
    ref: "GET /api/agent/tasks/team",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.agent_tasks.generate',
    label: "Generate — POST /api/agent/tasks/generate",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/agent/tasks/generate",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.agent_tasks.assign',
    label: "Assign — POST /api/agent/tasks/assign",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/agent/tasks/assign",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.agent_tasks_ai_generate.create',
    label: "Create — POST /api/agent/tasks/ai-generate",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/agent/tasks/ai-generate",
    cost: 'medium',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.agent_tasks_ai_commit.create',
    label: "Create — POST /api/agent/tasks/ai-commit",
    domain: 'admin',
    surface: 'api_route',
    ref: "POST /api/agent/tasks/ai-commit",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.admin_adoption.list',
    label: "List — GET /api/admin/adoption",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/admin/adoption",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.agent_approvals.list',
    label: "List — GET /api/agent/approvals",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/agent/approvals",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.agent_approvals.update',
    label: "Update — PUT /api/agent/approvals/:id",
    domain: 'admin',
    surface: 'api_route',
    ref: "PUT /api/agent/approvals/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.agent_activity.list',
    label: "List — GET /api/agent/activity",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/agent/activity",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.agent_dependencies.list',
    label: "List — GET /api/agent/dependencies",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/agent/dependencies",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.agent_overview.list',
    label: "List — GET /api/agent/overview",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/agent/overview",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'admin.agent_mission_control.list',
    label: "List — GET /api/agent/mission-control",
    domain: 'admin',
    surface: 'api_route',
    ref: "GET /api/agent/mission-control",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.linkedin.generate_post',
    label: "Generate post — POST /api/linkedin/generate-post",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/linkedin/generate-post",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.linkedin_content_queue.list',
    label: "List — GET /api/linkedin/content-queue",
    domain: 'growth',
    surface: 'api_route',
    ref: "GET /api/linkedin/content-queue",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.linkedin_content_queue.update',
    label: "Update — PUT /api/linkedin/content-queue/:id",
    domain: 'growth',
    surface: 'api_route',
    ref: "PUT /api/linkedin/content-queue/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.linkedin.publish',
    label: "Publish — POST /api/linkedin/publish/:id",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/linkedin/publish/:id",
    cost: 'free',
    spend: [],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.linkedin_run_campaign.create',
    label: "Create — POST /api/linkedin/run-campaign",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/linkedin/run-campaign",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.linkedin.generate_weekly',
    label: "Generate weekly — POST /api/linkedin/generate-weekly",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/linkedin/generate-weekly",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.linkedin.get_structure',
    label: "Get structure — POST /api/linkedin/get-structure/:cas_number",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/linkedin/get-structure/:cas_number",
    cost: 'high',
    spend: ['image'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.linkedin.regenerate_image',
    label: "Regenerate image — POST /api/linkedin/regenerate-image/:id",
    domain: 'growth',
    surface: 'api_route',
    ref: "POST /api/linkedin/regenerate-image/:id",
    cost: 'high',
    spend: ['image'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.linkedin_demand_molecules.list',
    label: "List — GET /api/linkedin/demand-molecules",
    domain: 'growth',
    surface: 'api_route',
    ref: "GET /api/linkedin/demand-molecules",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'growth.linkedin_analytics.list',
    label: "List — GET /api/linkedin/analytics",
    domain: 'growth',
    surface: 'api_route',
    ref: "GET /api/linkedin/analytics",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.research_intelligence_studies.list',
    label: "List — GET /api/research-intelligence/studies",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/research-intelligence/studies",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.research_intelligence_studies.get',
    label: "Get — GET /api/research-intelligence/studies/:id",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/research-intelligence/studies/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.research_intelligence.run',
    label: "Run — POST /api/research-intelligence/run",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/research-intelligence/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.research_intelligence_studies.find_contacts',
    label: "Find contacts — POST /api/research-intelligence/studies/:id/find-contacts",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/research-intelligence/studies/:id/find-contacts",
    cost: 'high',
    spend: ['apollo'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.research_intelligence_studies.resolve_org',
    label: "Resolve org — POST /api/research-intelligence/studies/:id/resolve-org",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/research-intelligence/studies/:id/resolve-org",
    cost: 'high',
    spend: ['apollo'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.research_intelligence_studies_contacts.get',
    label: "Get — GET /api/research-intelligence/studies/:id/contacts",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/research-intelligence/studies/:id/contacts",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.content.list',
    label: "List — GET /api/content",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/content",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.content.get',
    label: "Get — GET /api/content/:id",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "GET /api/content/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.content.update',
    label: "Update — PUT /api/content/:id (approve|reject|edit)",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "PUT /api/content/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'intelligence.content.run',
    label: "Run — POST /api/content/run",
    domain: 'intelligence',
    surface: 'api_route',
    ref: "POST /api/content/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.prospects.list',
    label: "List — GET /api/prospects",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/prospects",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.prospects.get',
    label: "Get — GET /api/prospects/:id",
    domain: 'revenue',
    surface: 'api_route',
    ref: "GET /api/prospects/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    key: 'revenue.prospects.update',
    label: "Update — PUT /api/prospects/:id (status + notes)",
    domain: 'revenue',
    surface: 'api_route',
    ref: "PUT /api/prospects/:id",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: false,
  },
  {
    // Places enumeration — external API cost, but NOT llm/apollo/email/image, so spend:[].
    key: 'revenue.prospects.run',
    label: "Run enumeration — POST /api/prospects/run",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/prospects/run",
    cost: 'high',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    // Booking-signature qualifier — free HTTP scraping, no spend.
    key: 'revenue.prospects.qualify',
    label: "Run qualifier — POST /api/prospects/qualify",
    domain: 'revenue',
    surface: 'api_route',
    ref: "POST /api/prospects/qualify",
    cost: 'high',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },

    // ===================== MCP TOOLS — outbound tool calls to product servers =====================
    // surface 'mcp_tool', ref = the JSON-RPC toolName (not an HTTP route, so the shadow/enforce
    // METHOD+path matcher never matches it). cost is what PLAYBOOKOS spends: publishing to
    // GolfNex costs us nothing (no model/credit/email) → cost:'free', spend:[]. dangerous:true
    // + defaultDeny:true carry the weight — it executes an action inside another product.
  {
    key: 'golfnex.content.publish_post',
    label: "Publish post — GolfNex MCP tool",
    domain: 'golfnex',
    surface: 'mcp_tool',
    ref: "publish_post",
    cost: 'free',
    spend: [],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },

    // ===================== AGENT TRIGGERS — mission-control manual runs (9) =====================
  {
    key: 'admin.agent_ceo.run',
    label: "Run CEO Agent (manual trigger)",
    domain: 'admin',
    surface: 'agent_trigger',
    ref: "POST /api/agent/mission-control/ceo-agent/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.agent_market_intelligence.run',
    label: "Run Market Intelligence (manual trigger)",
    domain: 'admin',
    surface: 'agent_trigger',
    ref: "POST /api/agent/mission-control/market-intelligence/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.agent_email_engine.run',
    label: "Run Email Engine (manual trigger)",
    domain: 'admin',
    surface: 'agent_trigger',
    ref: "POST /api/agent/mission-control/email-engine/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.agent_sales.run',
    label: "Run Sales Agent (manual trigger)",
    domain: 'admin',
    surface: 'agent_trigger',
    ref: "POST /api/agent/mission-control/sales-agent/run",
    cost: 'high',
    spend: ['apollo'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.agent_procurement.run',
    label: "Run Procurement Agent (manual trigger)",
    domain: 'admin',
    surface: 'agent_trigger',
    ref: "POST /api/agent/mission-control/procurement-agent/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.agent_meet.run',
    label: "Run Google Meet Agent (manual trigger)",
    domain: 'admin',
    surface: 'agent_trigger',
    ref: "POST /api/agent/mission-control/meet-agent/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.agent_research.run',
    label: "Run Research Agent (manual trigger)",
    domain: 'admin',
    surface: 'agent_trigger',
    ref: "POST /api/agent/mission-control/research-agent/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.agent_reorder.run',
    label: "Run Reorder Agent (manual trigger)",
    domain: 'admin',
    surface: 'agent_trigger',
    ref: "POST /api/agent/mission-control/reorder-agent/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.agent_inquiry.run',
    label: "Run Inquiry Agent (manual trigger)",
    domain: 'admin',
    surface: 'agent_trigger',
    ref: "POST /api/agent/mission-control/inquiry-agent/run",
    cost: 'high',
    spend: ['llm'],
    dangerous: true,
    implies: [],
    defaultDeny: true,
  },

    // ===================== AGENT TRIGGERS — crons (31, config toggles) =====================
  {
    key: 'intelligence.cron_daily_0utc_metrics_snapshot.toggle',
    label: "Cron: daily-0utc-metrics-snapshot (0 0 * * *)",
    domain: 'intelligence',
    surface: 'agent_trigger',
    ref: "daily-0utc-metrics-snapshot",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.cron_daily_7cst_command_center_briefing.toggle',
    label: "Cron: daily-7cst-command-center-briefing (0 7 * * 1-5)",
    domain: 'intelligence',
    surface: 'agent_trigger',
    ref: "daily-7cst-command-center-briefing",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'team.cron_weekly_mon_8utc_goal_engine.toggle',
    label: "Cron: weekly-mon-8utc-goal-engine (0 8 * * 1)",
    domain: 'team',
    surface: 'agent_trigger',
    ref: "weekly-mon-8utc-goal-engine",
    cost: 'medium',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.cron_weekly_mon_8utc_growth_agent.toggle',
    label: "Cron: weekly-mon-8utc-growth-agent (0 8 * * 1)",
    domain: 'growth',
    surface: 'agent_trigger',
    ref: "weekly-mon-8utc-growth-agent",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.cron_weekly_mon_8utc_seo_agent.toggle',
    label: "Cron: weekly-mon-8utc-seo-agent (0 8 * * 1)",
    domain: 'growth',
    surface: 'agent_trigger',
    ref: "weekly-mon-8utc-seo-agent",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'platform.cron_daily_8utc_github_sync.toggle',
    label: "Cron: daily-8utc-github-sync (0 8 * * *)",
    domain: 'platform',
    surface: 'agent_trigger',
    ref: "daily-8utc-github-sync",
    cost: 'free',
    spend: [],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.cron_weekly_mon_9utc_weekly_analysis.toggle',
    label: "Cron: weekly-mon-9utc-weekly-analysis (0 9 * * 1)",
    domain: 'intelligence',
    surface: 'agent_trigger',
    ref: "weekly-mon-9utc-weekly-analysis",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.cron_weekly_mon_9utc_revenue_intel.toggle',
    label: "Cron: weekly-mon-9utc-revenue-intel (0 9 * * 1)",
    domain: 'revenue',
    surface: 'agent_trigger',
    ref: "weekly-mon-9utc-revenue-intel",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.cron_weekly_mon_9cst_market_intelligence.toggle',
    label: "Cron: weekly-mon-9cst-market-intelligence (0 9 * * 1)",
    domain: 'intelligence',
    surface: 'agent_trigger',
    ref: "weekly-mon-9cst-market-intelligence",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.cron_weekly_mon_930cst_email_engine.toggle',
    label: "Cron: weekly-mon-930cst-email-engine (30 9 * * 1)",
    domain: 'revenue',
    surface: 'agent_trigger',
    ref: "weekly-mon-930cst-email-engine",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.cron_hourly_17_sales_replies.toggle',
    label: "Cron: hourly-17-sales-replies (17 * * * *)",
    domain: 'revenue',
    surface: 'agent_trigger',
    ref: "hourly-17-sales-replies",
    cost: 'high',
    spend: ['apollo'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'team.cron_daily_18utc_milestone_triggers.toggle',
    label: "Cron: daily-18utc-milestone-triggers (0 18 * * *)",
    domain: 'team',
    surface: 'agent_trigger',
    ref: "daily-18utc-milestone-triggers",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'team.cron_daily_18utc_performance_scoring.toggle',
    label: "Cron: daily-18utc-performance-scoring (0 18 * * *)",
    domain: 'team',
    surface: 'agent_trigger',
    ref: "daily-18utc-performance-scoring",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'team.cron_daily_18utc_goal_divergence.toggle',
    label: "Cron: daily-18utc-goal-divergence (0 18 * * *)",
    domain: 'team',
    surface: 'agent_trigger',
    ref: "daily-18utc-goal-divergence",
    cost: 'medium',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'procurement.cron_weekly_tue_9cst_procurement_rfqs.toggle',
    label: "Cron: weekly-tue-9cst-procurement-rfqs (0 9 * * 2)",
    domain: 'procurement',
    surface: 'agent_trigger',
    ref: "weekly-tue-9cst-procurement-rfqs",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.cron_daily_9cst_inquiry_agent.toggle',
    label: "Cron: daily-9cst-inquiry-agent (0 9 * * *)",
    domain: 'revenue',
    surface: 'agent_trigger',
    ref: "daily-9cst-inquiry-agent",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.cron_hourly_45_inquiry_poll.toggle',
    label: "Cron: hourly-45-inquiry-poll (45 * * * *)",
    domain: 'revenue',
    surface: 'agent_trigger',
    ref: "hourly-45-inquiry-poll",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.cron_weekly_wed_10cst_reorder_agent.toggle',
    label: "Cron: weekly-wed-10cst-reorder-agent (0 10 * * 3)",
    domain: 'revenue',
    surface: 'agent_trigger',
    ref: "weekly-wed-10cst-reorder-agent",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'revenue.cron_weekly_sun_20cst_reorder_agent.toggle',
    label: "Cron: weekly-sun-20cst-reorder-agent (0 20 * * 0)",
    domain: 'revenue',
    surface: 'agent_trigger',
    ref: "weekly-sun-20cst-reorder-agent",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.cron_nightly_23cst_research_agent.toggle',
    label: "Cron: nightly-23cst-research-agent (0 23 * * *)",
    domain: 'intelligence',
    surface: 'agent_trigger',
    ref: "nightly-23cst-research-agent",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.cron_weekly_mon_8cst_research_digest.toggle',
    label: "Cron: weekly-mon-8cst-research-digest (0 8 * * 1)",
    domain: 'intelligence',
    surface: 'agent_trigger',
    ref: "weekly-mon-8cst-research-digest",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.cron_daily_2cst_research_intel.toggle',
    label: "Cron: daily-2cst-research-intel (0 2 * * *)",
    domain: 'intelligence',
    surface: 'agent_trigger',
    ref: "daily-2cst-research-intel",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.cron_weekly_mon_11cst_meet_agent.toggle',
    label: "Cron: weekly-mon-11cst-meet-agent (0 11 * * 1)",
    domain: 'intelligence',
    surface: 'agent_trigger',
    ref: "weekly-mon-11cst-meet-agent",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.cron_weekly_fri_16cst_meet_agent.toggle',
    label: "Cron: weekly-fri-16cst-meet-agent (0 16 * * 5)",
    domain: 'intelligence',
    surface: 'agent_trigger',
    ref: "weekly-fri-16cst-meet-agent",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'intelligence.cron_biz_hours_2h_gemini_notes.toggle',
    label: "Cron: biz-hours-2h-gemini-notes (0 9,11,13,15,17 * * 1-5)",
    domain: 'intelligence',
    surface: 'agent_trigger',
    ref: "biz-hours-2h-gemini-notes",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'procurement.cron_weekly_thu_9cst_procurement_followup.toggle',
    label: "Cron: weekly-thu-9cst-procurement-followup (0 9 * * 4)",
    domain: 'procurement',
    surface: 'agent_trigger',
    ref: "weekly-thu-9cst-procurement-followup",
    cost: 'medium',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'procurement.cron_daily_2230cst_procurement_ist_briefing.toggle',
    label: "Cron: daily-2230cst-procurement-ist-briefing (30 22 * * *)",
    domain: 'procurement',
    surface: 'agent_trigger',
    ref: "daily-2230cst-procurement-ist-briefing",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.cron_daily_130cst_dev_seo_ist_briefing.toggle',
    label: "Cron: daily-130cst-dev-seo-ist-briefing (30 1 * * *)",
    domain: 'growth',
    surface: 'agent_trigger',
    ref: "daily-130cst-dev-seo-ist-briefing",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'admin.cron_daily_7cst_ceo_briefing.toggle',
    label: "Cron: daily-7cst-ceo-briefing (0 7 * * *)",
    domain: 'admin',
    surface: 'agent_trigger',
    ref: "daily-7cst-ceo-briefing",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'growth.cron_weekly_mon_10cst_linkedin_content.toggle',
    label: "Cron: weekly-mon-10cst-linkedin-content (0 10 * * 1)",
    domain: 'growth',
    surface: 'agent_trigger',
    ref: "weekly-mon-10cst-linkedin-content",
    cost: 'high',
    spend: ['llm', 'image'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },
  {
    key: 'team.cron_weekdays_8cst_us_team_briefing.toggle',
    label: "Cron: weekdays-8cst-us-team-briefing (0 8 * * 1-5)",
    domain: 'team',
    surface: 'agent_trigger',
    ref: "weekdays-8cst-us-team-briefing",
    cost: 'high',
    spend: ['llm'],
    dangerous: false,
    implies: [],
    defaultDeny: true,
  },

  ],
};

/*
 * UNGATED — NOT PERMISSION-CONTROLLED
 * These 7 routes carry gate:'none' and are intentionally omitted from FEATURES.
 *
 * IMPORTANT: "gate: none" here means NO EXPRESS MIDDLEWARE GATE (no authMiddleware /
 * requireTier / adminOnly). The P1 gate scan inspected middleware only, so it could not
 * see routes that authenticate INSIDE the handler. Several of these do exactly that —
 * via a shared-secret header or a signature check — so the "none" label understates their
 * actual protection. Only /auth/login and /auth/accept-invite are genuinely public.
 *
 *   POST /api/auth/login              — genuinely public: login
 *   POST /api/auth/accept-invite      — genuinely public: gated by the invite token in the body
 *   POST /api/orders/webhook          — in-handler: X-PlaybookOS-Secret === PLAYBOOKOS_WEBHOOK_SECRET (401/503)
 *   POST /api/customers/engagement-event — in-handler: X-Engagement-Secret === ENGAGEMENT_SECRET (401/503)
 *   POST /api/inquiry/receive         — in-handler: X-PlaybookOS-Secret === PLAYBOOKOS_WEBHOOK_SECRET (401/503)
 *   POST /api/inquiry/stripe-webhook  — in-handler: Stripe HMAC signature verification (see e0ce480)
 *   POST /api/triggers/check          — in-handler: Authorization: Bearer ${TRIGGERS_SECRET}
 *                                        (routes.js:762-766; 401 on mismatch, 503 if unset). Called by the
 *                                        daily-18utc-milestone-triggers cron over HTTP localhost
 *                                        (server.js:239). Runs checkMilestoneTriggers (jobs.js:88) —
 *                                        email + DB writes only, NO LLM. (The earlier "mis-gated /
 *                                        reaches LLM spend" note was wrong on both counts — corrected here.)
 */
